### ISSUE TITLE
tmux-conf

### ISSUE THREAD

**Issue by diek** [chriskuehl/dotfiles#4]
I do appreciate you sharing your tmux.conf, I am confused about the purpose of your final line.

source ~/.tmux-local.conf

**Comment by chriskuehl** [comment]
It loads another config file which isn't checked in to this dotfiles repo. I sometimes use this pattern so that I can have special per-machine configuration when needed, since I tend to use my dotfiles across a lot of machines and they sometimes need slight settings tweaks. If you don't need your config to change across multiple machines you can just delete that line.

I think I originally introduced this because I was using a special config for macOS hosts: https://github.com/chriskuehl/dotfiles/blob/master/tmux-osx.conf

I don't really remember the original reason though.
